jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        name: ${ADMIN_NAME}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: http://localhost:8080/
  gitHubPluginConfig:
    configs:
    - name: Github
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: github-credentials
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          description: GitHub Personal Access Token
      - string:
          scope: GLOBAL
          id: google-api-key
          secret: ${GOOGLE_API_KEY}
          description: Google API Key
      - string:
          scope: GLOBAL
          id: google-api-key-alt
          secret: ${GOOGLE_API_KEY_ALT}
          description: Google API Key Alternative
      - string:
          scope: GLOBAL
          id: openai-api-key
          secret: ${OPENAI_API_KEY}
          description: OpenAI API Key
      - string:
          scope: GLOBAL
          id: together-api-key
          secret: ${TOGETHER_API_KEY}
          description: TogetherAI API Key
      - string:
          scope: GLOBAL
          id: anthropic-api-key
          secret: ${ANTHROPIC_API_KEY}
          description: Anthropic API Key
      - string:
          scope: GLOBAL
          id: deepseek-api-key
          secret: ${DEEPSEEK_API_KEY}
          description: DeepSeek API Key
      - string:
          scope: GLOBAL
          id: huggingface-api-key
          secret: ${HUGGINGFACE_API_KEY}
          description: HuggingFace API Key
      - string:
          scope: GLOBAL
          id: ollama-api-key
          secret: ${OLLAMA_API_KEY}
          description: Ollama API Key

jobs:
  - script: >
      pipelineJob('ai-gym-pt-main') {
        triggers {
          scm('*/1 * * * *')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/HariSeldon86/ai-gym-pt.git')
                  credentials('github-credentials')
                }
                branches('main')
              }
            }
            scriptPath('jenkins/Jenkinsfile')
          }
        }
      }
